import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Post from '../components/Post'
import PostForm from '../components/PostForm'
import Bio from '../components/Bio'
export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Bio
          name='Mazo'
          headshot='https://thispersondoesnotexist.com/image'
          tagline="hard work beats talent when talent doesn't work hard"
          role='a Son, a Father and a whole stack developer'

        />

        <ul className={styles.posts}>

          <li>
            <Post
              content='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sem orci, mollis et orci eu, suscipit bibendum massa. Integer blandit ut tortor sit amet fermentum.'
              date='26/9/2021'
            />

          </li>
          <li>
            <Post
              content='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sem orci, mollis et orci eu, suscipit bibendum massa. Integer blandit ut tortor sit amet fermentum.'
              date='26/9/2021'
            />
          </li>
          <li>
            <Post
              content='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sem orci, mollis et orci eu, suscipit bibendum massa. Integer blandit ut tortor sit amet fermentum.'
              date='26/9/2021'
            />
          </li>
        </ul>
        <PostForm />
      </main>
    </div>
  )
}
